#define DISTRHO_PLUGIN_NAME "minisilver"

#define DISTRHO_PLUGIN_NUM_INPUTS 0

#define DISTRHO_PLUGIN_NUM_OUTPUTS 2

#define DISTRHO_PLUGIN_URI "urn:minisilver"

#define DISTRHO_PLUGIN_HAS_UI 1

#define DISTRHO_PLUGIN_IS_RT_SAFE 1

#define DISTRHO_PLUGIN_IS_SYNTH 1

#define DISTRHO_PLUGIN_WANT_DIRECT_ACCESS 1

#define DISTRHO_PLUGIN_WANT_LATENCY 0

#define DISTRHO_PLUGIN_WANT_MIDI_INPUT 1

#define DISTRHO_PLUGIN_WANT_MIDI_OUTPUT 0

#define DISTRHO_PLUGIN_WANT_PARAMETER_VALUE_CHANGE_REQUEST 0

#define DISTRHO_PLUGIN_WANT_PROGRAMS 0

#define DISTRHO_PLUGIN_WANT_STATE 0

#define DISTRHO_PLUGIN_WANT_FULL_STATE 0

#define DISTRHO_PLUGIN_WANT_TIMEPOS 0

#define DISTRHO_UI_USE_CUSTOM 1

#define DISTRHO_UI_CUSTOM_INCLUDE_PATH "DearImGui.hpp"

#define DISTRHO_UI_CUSTOM_WIDGET_TYPE DGL_NAMESPACE::ImGuiTopLevelWidget

#define DISTRHO_UI_DEFAULT_WIDTH 730

#define DISTRHO_UI_DEFAULT_HEIGHT 460

#define DISTRHO_UI_USE_NANOVG 0

#define DISTRHO_UI_USER_RESIZABLE 1

#define DISTRHO_UI_URI DISTRHO_PLUGIN_URI "#UI"

#define DISTRHO_PLUGIN_LV2_CATEGORY "lv2:InstrumentPlugin"

#define DISTRHO_PLUGIN_VST3_CATEGORIES "Instrument|Synth"

#define DISTRHO_PLUGIN_CLAP_FEATURES "audio-instrument", "synthesizer", "stereo"

#define DISTRHO_PLUGIN_CLAP_ID "simonl.minisilver"
